'Code by @ClintBrown3D
'Originally posted at https://clintbrown.co.uk/ilogic-properties-tool-tip-3
'This is an updated version of the code found here: https://clintbrown.co.uk/iproperty-tool-tip-with-ilogic-updated

'In√≠cio da execu√ß√£o
TheStart:
On Error GoTo ClintBrown3D 'Define o comportamento em caso de erro

'Obt√©m o documento ativo no Inventor
Dim doc = ThisApplication.ActiveDocument

'Permite que o usu√°rio selecione uma ocorr√™ncia de montagem (parte) na √°rvore de componentes
Dim entity = ThisApplication.CommandManager.Pick(SelectionFilterEnum.kAssemblyLeafOccurrenceFilter, "Selecione uma pe√ßa üôÇ - ou ESC para sair")

'Verifica se a sele√ß√£o foi feita (se a entidade n√£o √© nada)
If (Not entity Is Nothing) Then
    'Obt√©m informa√ß√µes da pe√ßa selecionada a partir de suas propriedades de projeto
    oOne = "Part Number: " & iProperties.Value(entity.Name, "Project", "Part Number") 'N√∫mero da pe√ßa
    oTwo = "Mass: " & Round(iProperties.MassOfComponent(entity.Name), 2) & " kg" 'Massa da pe√ßa
    oThree = "Material: " & iProperties.MaterialOfComponent(entity.Name) 'Material da pe√ßa
    oFour = "Designer: " & iProperties.Value(entity.Name, "Project", "Designer") 'Designer da pe√ßa
    oFive = "Description: " & iProperties.Value(entity.Name, "Project", "Description") 'Descri√ß√£o da pe√ßa
    
    'Se a descri√ß√£o estiver vazia, mostra o nome do arquivo no campo de descri√ß√£o
    If iProperties.Value(entity.Name, "Project", "Description") = "" Then : oFive = "Description: " & entity.Name : End If

    'Cria√ß√£o de um conjunto de destaque para a pe√ßa selecionada
    Dim oSet1 As HighlightSet  
    oSet1 = doc.CreateHighlightSet 'Cria um conjunto de destaque
    oSet1.Color = ThisApplication.TransientObjects.CreateColor(255, 125, 0) 'Define a cor do destaque
    Call oSet1.AddItem(entity) 'Adiciona a pe√ßa ao conjunto de destaque

    'Exibe um prompt de sele√ß√£o ao usu√°rio, mostrando as informa√ß√µes da pe√ßa selecionada
    bob = ThisApplication.CommandManager.Pick(SelectionFilterEnum.kAssemblyLeafOccurrenceFilter, (oOne & " - " & oTwo & " - "  & oThree & " - "  & oFour & " - "  & oFive))
    bob = "" 'Limpa a vari√°vel 'bob' ap√≥s a sele√ß√£o
    Call oSet1.Clear 'Limpa o conjunto de destaque ap√≥s a sele√ß√£o
End If

'Se a sele√ß√£o n√£o for feita (ESC pressionado), permite que o c√≥digo saia
If (Not entity Is Nothing) Then  
    'Retorna ao in√≠cio do processo para permitir uma nova sele√ß√£o
    GoTo TheStart:
End If

'Finaliza o c√≥digo
Return 

'Caso ocorra um erro, o controle ser√° transferido para aqui
ClintBrown3D:
